In [68]:
import pandas as pd
import numpy as np

from datetime import datetime, timedelta
from tqdm import tqdm

save_path = "C:\\Users\\Happy\\Desktop\\맹박사님\\data\\"

In [65]:
pd.__version__

'2.0.3'

Collecting pandas==1.5.3
  Using cached pandas-1.5.3-cp311-cp311-win_amd64.whl (10.3 MB)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\happy\anaconda3\lib\site-packages (from pandas==1.5.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\happy\anaconda3\lib\site-packages (from pandas==1.5.3) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\happy\anaconda3\lib\site-packages (from pandas==1.5.3) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\happy\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas==1.5.3) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3

ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'C:\\Users\\Happy\\anaconda3\\Lib\\site-packages\\~andas\\_libs\\algos.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [52]:
# !pip install xlrd
# !pip install openpyxl
# !pip install pandas

In [53]:
KRW_USDT_before = pd.read_excel(save_path+"ALL_DATA_KOSPI_future_목시수종_조기정.xlsx" )#,encoding = "cp949",names = ['날짜',"오픈","고가","저가","종가"]

In [54]:
"""
선물지수 3주 이동평균선
"""
KRW_USDT_before # 3주 이평 수요일 ... # 2022 10월 12일 open종가 고가?

,만기전일,만기일,선물만기일_시가,만기일개장시_등가,만기전일_선물종가,단순이동평균_종가,지수이동평균_종가,가중이동평균_종가,최소제곱평균_종가,삼각이동평균_종가,만기전일_선물종가-단순이동평균_종가,만기전일_선물종가-지수이동평균_종가,만기전일_선물종가-가중이동평균_종가,만기전일_선물종가-최소제곱평균_종가,만기전일_선물종가-삼각이동평균_종가,단순이동평균_포지션,지수이동평균_포지션,가중이동평균_포지션,최소제곱평균_포지션,삼각이동평균_포지션
0,2023-10-25,2023-10-26,312.95,312.5,317.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-10-18,2023-10-19,326.50,327.5,330.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-10-11,2023-10-12,328.70,327.5,327.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-10-04,2023-10-05,322.00,322.5,320.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-09-26,2023-09-27,326.10,325.0,328.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,2019-10-23,2019-10-24,277.80,277.5,276.65,274.65,275.144547,275.70,277.80,274.40,2.00,1.51,0.95,-1.15,2.25,상방,상방,상방,하방,상방
211,2019-10-16,2019-10-17,277.35,277.5,276.95,271.98,273.639095,273.37,276.13,271.36,4.97,3.31,3.58,0.82,5.59,상방,상방,상방,상방,상방
212,2019-10-10,2019-10-10,268.20,267.5,270.35,271.18,270.328189,270.48,269.08,271.29,-0.83,0.02,-0.13,1.27,-0.94,하방,상방,하방,상방,하방
213,2019-10-02,2019-10-02,272.75,272.5,268.65,272.18,270.306379,271.40,269.83,272.63,-3.53,-1.66,-2.75,-1.18,-3.98,하방,하방,하방,하방,하방
214,2019-09-25,2019-09-26,275.45,275.0,274.55,273.07,271.962758,273.61,274.69,272.88,1.48,2.59,0.94,-0.14,1.67,상방,상방,상방,하방,상방

In [148]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\happy\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\happy\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\happy\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\happy\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\happy\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [149]:
import pandas as pd

In [150]:
# yes traider 파일
KRW_USDT = pd.read_csv(save_path+"코스피200 선물 (F) 선물 과거 데이터 (1).csv") #  , encoding = "cp949",names = ['날짜',"오픈","고가","저가","종가"]
KRW_USDT

                날짜      종가      시가      고가      저가      거래량    변동 %
0     2023- 12- 08  337.25  334.80  337.65  334.70  224.53K   1.46%
1     2023- 12- 07  332.40  331.80  334.10  331.50  237.10K  -0.33%
2     2023- 12- 06  333.50  333.80  335.95  333.50  210.17K   0.26%
3     2023- 12- 05  332.65  334.15  335.35  332.65  215.34K  -1.20%
4     2023- 12- 04  336.70  337.05  338.30  336.00  219.00K   0.36%
...            ...     ...     ...     ...     ...      ...     ...
3535  2009- 11- 24  212.23  214.88  215.10  211.23      NaN  -0.86%
3536  2009- 11- 23  214.08  214.53  215.28  213.03      NaN   0.02%
3537  2009- 11- 22  214.03  214.03  214.03  214.03      NaN   0.02%
3538  2009- 11- 20  213.98  213.13  214.63  212.78      NaN   0.07%
3539  2009- 11- 19  213.83  211.85  214.73  211.85      NaN   1.09%

[3540 rows x 7 columns]

In [151]:
KRW_USDT  = KRW_USDT.rename(columns = {"시가":"오픈"})

In [152]:

def Pretreatment_by_yes_trader(df): #데이터 가이드에서 다운한 데이터 전처리
    df["날짜"] = [df["날짜"][i][0:4]+"-"+df["날짜"][i][6:8]+"-"+df["날짜"][i][10:12] for i in range(len(df["날짜"]))]
    df['날짜'] = pd.to_datetime(df['날짜'], format='%Y-%m-%d', errors='raise')
    
    # 예스트레이더는 장이 열려있으면 데이터를 이상하게 주기 떄문에 중복제거, 인덱스 초기화 를 하였음
    df = df.sort_values(['날짜'],ascending= True).drop_duplicates('날짜').reset_index(drop = True).rename(columns={'날짜':'time'})
    
    return df

df = Pretreatment_by_yes_trader(KRW_USDT)

In [153]:
df

           time      종가      오픈      고가      저가      거래량    변동 %
0    2009-11-19  213.83  211.85  214.73  211.85      NaN   1.09%
1    2009-11-20  213.98  213.13  214.63  212.78      NaN   0.07%
2    2009-11-22  214.03  214.03  214.03  214.03      NaN   0.02%
3    2009-11-23  214.08  214.53  215.28  213.03      NaN   0.02%
4    2009-11-24  212.23  214.88  215.10  211.23      NaN  -0.86%
...         ...     ...     ...     ...     ...      ...     ...
3535 2023-12-04  336.70  337.05  338.30  336.00  219.00K   0.36%
3536 2023-12-05  332.65  334.15  335.35  332.65  215.34K  -1.20%
3537 2023-12-06  333.50  333.80  335.95  333.50  210.17K   0.26%
3538 2023-12-07  332.40  331.80  334.10  331.50  237.10K  -0.33%
3539 2023-12-08  337.25  334.80  337.65  334.70  224.53K   1.46%

[3540 rows x 7 columns]

In [161]:
df = df[["time","종가","오픈","고가","저가"]]
df["day_of_year"] = df.time.dt.day_of_year
df["weekofyear"] = df.time.dt.isocalendar().week
df["year"] = df.time.dt.year
df["day_of_week"] = df.time.dt.day_of_week
df["year_of_month"]  = df.time.dt.month

C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\3609631407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["day_of_year"] = df.time.dt.day_of_year
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\3609631407.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["weekofyear"] = df.time.dt.isocalendar().week
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\3609631407.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year"] = df.time.dt.year
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\3609631407.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["day_of_week"] = df.time.dt.day_of_week

In [166]:
df.loc[(df.year_of_month == 12)&(df.weekofyear == 1)]

,time,종가,오픈,고가,저가,day_of_year,weekofyear,year,day_of_week,year_of_month
818,2012-12-31,265.98,265.98,265.98,265.98,366,1,2012,0,12
1072,2013-12-30,265.65,266.30,266.45,265.05,364,1,2013,0,12
1332,2014-12-29,247.40,249.60,249.85,247.40,363,1,2014,0,12
1333,2014-12-30,244.00,247.65,248.30,244.00,364,1,2014,1,12
2565,2019-12-30,295.20,295.80,296.55,294.85,364,1,2019,0,12

In [167]:
df.loc[(df.year_of_month == 12)&(df.weekofyear == 1),"weekofyear"] = 53

def weekofyear_(date):
    if ((date.month == 12) & (date.weekofyear== 1)):
         return 53
    else:
        return date.weekofyear

In [168]:
df.to_csv("rowdata_spot.csv", encoding = "cp949")
df = df.drop_duplicates()

In [169]:
df.columns

Index(['time', '종가', '오픈', '고가', '저가', 'day_of_year', 'weekofyear', 'year',
       'day_of_week', 'year_of_month'],
      dtype='object')

In [170]:
def out_put(df, start_dayofweek=4, end_dayofweek=3):
    info = {"time": 0, "오픈": 0, "저가": 0, "고가": 0, "종가": None, "시작일": 0}
    info_dataFrame = pd.DataFrame(info, index=[0])

    df1 = df[["year", "weekofyear"]].drop_duplicates()

    for i in tqdm(range(len(df1))):
#     for i in range(len(df1)):

        df_strat_day = df.loc[(df1.iloc[i, :].year == df.year) & (df1.iloc[i, :].weekofyear == df.weekofyear)].time.iloc[0]  # 시작일
        while True:
            new_df_1 = df.loc[(df.year == df_strat_day.year) & (df.weekofyear == weekofyear_(df_strat_day))]
            if len(new_df_1) == 0:
                print(df_strat_day, "맨처음 시작일이 시작 요일(목)이 없을 경우")
                df_strat_day = df_strat_day - timedelta(weeks=1)
            elif len(new_df_1) >= 1:
                break
        ww = start_dayofweek
        while True:

            new_df = new_df_1.loc[(new_df_1.day_of_week == ww)]
            if (len(new_df) == 0):
                ww = ww - 1
            if len(new_df) == 1:
                break
            if ww == -1:
                break  # 이부분은 이전주로 가야함.

        if (ww == -1) and len(new_df_1) >= 1:
            #             print("지울것. 다른요일만 남은날")
            wk = 6
            while True:
                new_df = new_df_1.loc[(new_df_1.day_of_week == wk)]
                if (len(new_df) == 0):
                    wk = wk - 1
                if len(new_df) == 1:
                    break
                if wk == -1:
                    break  # 이부분은 이전주로 가야함.

        if len(new_df_1) == 0:
            print(df_strat_day, "맨처음 볼 테이블이 없음")

        else:
            df_end_day = df_strat_day = new_df.time.iloc[0]
            df_end_day = df_end_day + timedelta(weeks=1)

            while True:
                new_df_1 = df.loc[(df.year == df_end_day.year) & (df.weekofyear == weekofyear_(df_end_day))]
                if len(new_df_1) == 0:
#                     print(df_end_day, "끝나는 요일이 시작 요일(금)이 없을 경우")
                    df_end_day = df_end_day + timedelta(weeks=1)

                if (df.iloc[len(df) - 1, :].time < df_end_day):

                    return info_dataFrame[1:].sort_values(by=["time"]).reset_index(drop=True)

                elif len(new_df_1) >= 1:
                    if (new_df_1.time.iloc[0] < df_strat_day):  # 해년도를 넘어간 경우
                        print("해년도를 넘어간 경우", i)
                        df_end_day = df_end_day + timedelta(weeks=1)
                        #                         new_df_1 = df.loc[(df.year == df_end_day.year) & (df.weekofyear == df_end_day.weekofyear)&(df.time < df_end_day)]
                        new_df_1 = df.loc[(df.year == df_end_day.year) & (df.weekofyear == weekofyear_(df_end_day))]
                    break

            wk = end_dayofweek
            while True:  # 다음다음다음 날들을 찾음. 다 없으면 종료..
                new_df = new_df_1.loc[(new_df_1.day_of_week == wk)]
                if (len(new_df) == 0):
                    wk = wk + 1
                if len(new_df) == 1:
                    break
                if wk == 7:
                    #                     if (new_df_1.time.iloc[0] < df_strat_day): # 해년도를 넘어간 경우
                    #                         print("해년도를 넘어간 경우",i)
                    #                         df_end_day = df_end_day + timedelta(weeks = 1)
                    #                         new_df_1 = df.loc[(df.year == df_end_day.year) & (df.weekofyear == df_end_day.weekofyear)]
                    break  # 이부분은 이전주로 가야함.

            if (wk == 7) and len(new_df_1) >= 1:  #
                #     print("지울것. 금요일만 남은낧",i)
                while True:  # 1일 이상인 다음주를 찾음.
                    df_end_day = df_end_day + timedelta(weeks=1)
                    new_df_1 = df.loc[(df.year == df_end_day.year) & (df.weekofyear == weekofyear_(df_end_day))]
                    if len(new_df_1) >= 1:
                        break

                wk = 0
                while True:
                    new_df = new_df_1.loc[(new_df_1.day_of_week == wk)]
                    if (len(new_df) == 0):
                        wk = wk + 1
                    if len(new_df) == 1:
                        break
                #                 if (new_df_1.time.iloc[0] < df_strat_day): # 해년도를 넘어간 경우

                #                     print("해년도를 넘어간 경우",i)
                #                     df_end_day = df_end_day + timedelta(weeks = 1)
                #                     new_df_1 = df.loc[(df.year == df_end_day.year) & (df.weekofyear == df_end_day.weekofyear)]
                # elif
                # wk == 7:
                

        if len(new_df_1) == 0:
            print(df_end_day, "맨 마지막 볼 테이블이 없음",i)
        if len(new_df) == 0:
            print(df_end_day, "맨 마지막 볼 테이블이 없음",i)
        else:
            df_end_day = new_df.time.iloc[0]

            df_table = df.loc[(df.time.between(df_strat_day, df_end_day))]

#             if len(df_table) >= 6:
#                 print(i, "========",df_table)

            info = {"time": df_end_day, "오픈": df_table.iloc[0,].오픈, "저가": min(df_table.저가.values), "고가": max(df_table.고가.values), "종가": df_table[df_table.time == df_end_day].오픈.iloc[0], "시작일": df_strat_day}
            new_info_dataFrame = pd.DataFrame(info, index=[0])
            info_dataFrame = pd.concat([info_dataFrame, new_info_dataFrame], axis=0)  # 수익 데이터 저장


    return info_dataFrame[1:].sort_values(by=["time"]).reset_index(drop=True)

In [171]:
# 0월 1화 2수 3목 4금 5토 6일
info_dataFrame = out_put(df, start_dayofweek = 3, end_dayofweek = 3)
# info_dataFrame.to_csv("info_dataFrame.csv", encoding = "cp949")

100%|██████████████████████████████████████████████████████████████████████████████▉| 737/738 [00:05<00:00, 135.74it/s]

In [172]:
# info_dataFrame = info_dataFrame.rename(columns = {"진입시점":"시작일"})
info_dataFrame["timedelta"] = info_dataFrame["time"] - info_dataFrame["시작일"]
info_dataFrame['시작일'] = pd.to_datetime(info_dataFrame['시작일'], format='%Y-%m-%d', errors='raise')

In [173]:
for i in range(len(info_dataFrame)):
    df_table = df.loc[(df.time.between(info_dataFrame.iloc[i].시작일,info_dataFrame.iloc[i].time))]
    if len(df_table) >= 7:
        
        print(df_table)
        print(i,"========")

        time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
0 2009-11-19  213.83  211.85  214.73  211.85          323          47  2009
1 2009-11-20  213.98  213.13  214.63  212.78          324          47  2009
2 2009-11-22  214.03  214.03  214.03  214.03          326          47  2009
3 2009-11-23  214.08  214.53  215.28  213.03          327          48  2009
4 2009-11-24  212.23  214.88  215.10  211.23          328          48  2009
5 2009-11-25  212.73  212.68  213.03  211.28          329          48  2009
6 2009-11-26  210.93  212.18  214.03  210.63          330          48  2009

   day_of_week  year_of_month
0            3             11
1            4             11
2            6             11
3            0             11
4            1             11
5            2             11
6            3             11
0 ========
         time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
6  2009-11-26  210.93  212.18  214.03  210.63          330          48  2009
7  2009-11-27  201.63  207.15  208.23  200.03          331          48  2009
8  2009-11-29  201.63  201.63  201.63  201.63          333          48  2009
9  2009-11-30  203.98  204.05  206.73  203.65          334          49  2009
10 2009-12-01  206.78  203.98  207.28  203.03          335          49  2009
11 2009-12-02  210.28  208.28  210.88  208.18          336          49  2009
12 2009-12-03  213.58  211.25  213.73  210.73          337          49  2009

    day_of_week  year_of_month
6             3             11
7             4             11
8             6             11
9             0             11
10            1             12
11            2             12
12            3             12
1 ========
         time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
12 2009-12-03  213.58  211.25  213.73  210.73          337          49  2009
13 2009-12-04  214.78  212.73  215.58  212.68          338          49  2009
14 2009-12-06  214.93  214.93  214.93  214.93          340          49  2009
15 2009-12-07  215.48  215.83  216.13  214.68          341          50  2009
16 2009-12-08  215.18  215.28  216.43  214.38          342          50  2009
17 2009-12-09  215.88  213.48  216.08  212.63          343          50  2009
18 2009-12-10  215.98  215.80  216.83  212.58          344          50  2009

    day_of_week  year_of_month
12            3             12
13            4             12
14            6             12
15            0             12
16            1             12
17            2             12
18            3             12
2 ========
         time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
18 2009-12-10  215.98  215.80  216.83  212.58          344          50  2009
19 2009-12-11  217.33  216.33  218.53  215.13          345          50  2009
20 2009-12-13  217.23  217.23  217.23  217.23          347          50  2009
21 2009-12-14  217.93  217.78  218.38  215.13          348          51  2009
22 2009-12-15  218.18  217.73  218.28  216.68          349          51  2009
23 2009-12-16  217.93  218.13  218.78  216.13          350          51  2009
24 2009-12-17  215.18  217.73  217.98  215.18          351          51  2009

    day_of_week  year_of_month
18            3             12
19            4             12
20            6             12
21            0             12
22            1             12
23            2             12
24            3             12
3 ========
         time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
24 2009-12-17  215.18  217.73  217.98  215.18          351          51  2009
25 2009-12-18  214.85  214.53  215.83  213.28          352          51  2009
26 2009-12-20  214.88  214.88  214.88  214.88          354          51  2009
27 2009-12-21  214.83  214.73  215.73  213.58          355          52  2009
28 2009-12-22  216.98  216.33  216.98  215.43          356          52  2009
29 2009-12-23  217.73  217.38  217.93  216.83          357          52  2009
30 2009-12-24  221.08  218.08  221.93  217.83          358          52  2009

    day_of_week  year_of_month
24            3             12
25            4             12
26            6             12
27            0             12
28            1             12
29            2             12
30            3             12
4 ========
         time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
55 2010-01-28  215.28  213.53  216.33  212.43           28           4  2010
56 2010-01-29  210.03  212.63  213.38  209.33           29           4  2010
57 2010-01-31  209.88  209.88  209.88  209.88           31           4  2010
58 2010-02-01  209.88  209.53  211.28  208.68           32           5  2010
59 2010-02-02  208.68  211.03  211.78  208.35           33           5  2010
60 2010-02-03  211.38  211.08  211.93  209.58           34           5  2010
61 2010-02-04  210.78  211.35  211.78  210.13           35           5  2010

    day_of_week  year_of_month
55            3              1
56            4              1
57            6              1
58            0              2
59            1              2
60            2              2
61            3              2
11 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
138 2010-05-27  211.98  204.23  211.98  203.68          147          21  2010
139 2010-05-28  211.38  211.93  211.98  209.63          148          21  2010
140 2010-05-30  212.15  211.93  212.15  211.93          150          21  2010
141 2010-05-31  213.23  212.13  213.68  211.43          151          22  2010
142 2010-06-01  211.43  212.60  213.63  211.43          152          22  2010
143 2010-06-02  211.43  211.43  211.43  211.43          153          22  2010
144 2010-06-03  217.23  214.28  217.98  213.88          154          22  2010

     day_of_week  year_of_month
138            3              5
139            4              5
140            6              5
141            0              5
142            1              6
143            2              6
144            3              6
28 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
144 2010-06-03  217.23  214.28  217.98  213.88          154          22  2010
145 2010-06-04  218.53  217.18  218.53  216.85          155          22  2010
146 2010-06-06  213.93  213.70  213.93  213.70          157          22  2010
147 2010-06-07  214.33  213.98  214.63  211.88          158          23  2010
148 2010-06-08  215.73  214.28  216.93  212.93          159          23  2010
149 2010-06-09  216.55  215.68  216.90  214.13          160          23  2010
150 2010-06-10  219.58  216.48  219.58  214.93          161          23  2010

     day_of_week  year_of_month
144            3              6
145            4              6
146            6              6
147            0              6
148            1              6
149            2              6
150            3              6
29 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
150 2010-06-10  219.58  216.48  219.58  214.93          161          23  2010
151 2010-06-11  220.13  219.48  220.58  217.98          162          23  2010
152 2010-06-13  221.03  220.83  221.08  220.83          164          23  2010
153 2010-06-14  221.63  221.23  223.68  221.18          165          24  2010
154 2010-06-15  224.43  221.53  224.63  221.28          166          24  2010
155 2010-06-16  224.13  224.33  224.93  223.18          167          24  2010
156 2010-06-17  224.98  224.05  225.08  223.83          168          24  2010

     day_of_week  year_of_month
150            3              6
151            4              6
152            6              6
153            0              6
154            1              6
155            2              6
156            3              6
30 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
156 2010-06-17  224.98  224.05  225.08  223.83          168          24  2010
157 2010-06-18  224.73  225.03  225.13  223.68          169          24  2010
158 2010-06-20  227.48  227.53  227.63  227.43          171          24  2010
159 2010-06-21  226.73  227.53  229.23  226.43          172          25  2010
160 2010-06-22  226.38  226.83  227.88  226.23          173          25  2010
161 2010-06-23  225.73  226.48  227.58  225.73          174          25  2010
162 2010-06-24  226.08  225.78  228.58  225.68          175          25  2010

     day_of_week  year_of_month
156            3              6
157            4              6
158            6              6
159            0              6
160            1              6
161            2              6
162            3              6
31 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
167 2010-07-01  218.83  219.68  220.58  216.43          182          26  2010
168 2010-07-02  217.33  219.28  219.90  216.98          183          26  2010
169 2010-07-04  218.08  217.33  218.08  217.33          185          26  2010
170 2010-07-05  217.73  218.03  218.43  216.73          186          27  2010
171 2010-07-06  218.68  215.90  219.23  214.13          187          27  2010
172 2010-07-07  217.88  218.48  218.48  216.48          188          27  2010
173 2010-07-08  222.33  220.83  222.78  220.43          189          27  2010

     day_of_week  year_of_month
167            3              7
168            4              7
169            6              7
170            0              7
171            1              7
172            2              7
173            3              7
33 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
173 2010-07-08  222.33  220.83  222.78  220.43          189          27  2010
174 2010-07-09  225.33  222.38  225.33  221.28          190          27  2010
175 2010-07-11  225.68  225.18  226.08  225.18          192          27  2010
176 2010-07-12  227.08  225.78  227.13  225.08          193          28  2010
177 2010-07-13  230.03  227.13  230.13  226.73          194          28  2010
178 2010-07-14  230.38  229.98  231.43  229.98          195          28  2010
179 2010-07-15  229.53  229.83  230.58  229.28          196          28  2010

     day_of_week  year_of_month
173            3              7
174            4              7
175            6              7
176            0              7
177            1              7
178            2              7
179            3              7
34 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
179 2010-07-15  229.53  229.83  230.58  229.28          196          28  2010
180 2010-07-16  227.53  229.28  229.93  227.18          197          28  2010
181 2010-07-18  227.33  227.33  227.33  227.33          199          28  2010
182 2010-07-19  225.98  224.60  227.33  224.08          200          29  2010
183 2010-07-20  226.28  224.98  227.03  224.38          201          29  2010
184 2010-07-21  228.33  229.10  229.18  226.93          202          29  2010
185 2010-07-22  226.63  227.68  229.08  226.63          203          29  2010

     day_of_week  year_of_month
179            3              7
180            4              7
181            6              7
182            0              7
183            1              7
184            2              7
185            3              7
35 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
189 2010-07-27  231.68  231.88  232.33  231.33          208          30  2010
190 2010-07-30  230.18  231.73  232.08  229.83          211          30  2010
191 2010-08-01  230.08  230.08  230.08  230.08          213          30  2010
192 2010-08-02  233.33  231.48  233.73  231.28          214          31  2010
193 2010-08-03  234.13  234.33  234.48  233.73          215          31  2010
194 2010-08-04  233.68  234.43  234.48  232.58          216          31  2010
195 2010-08-05  233.63  234.88  235.18  232.18          217          31  2010

     day_of_week  year_of_month
189            1              7
190            4              7
191            6              8
192            0              8
193            1              8
194            2              8
195            3              8
37 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
200 2010-08-12  224.58  225.88  226.73  224.28          224          32  2010
201 2010-08-13  226.83  224.78  227.18  224.28          225          32  2010
202 2010-08-15  226.58  226.58  226.58  226.58          227          32  2010
203 2010-08-16  226.68  225.28  226.68  222.73          228          33  2010
204 2010-08-17  228.58  224.93  228.58  224.58          229          33  2010
205 2010-08-18  229.08  228.85  229.23  227.68          230          33  2010
206 2010-08-19  232.28  228.78  232.63  228.68          231          33  2010

     day_of_week  year_of_month
200            3              8
201            4              8
202            6              8
203            0              8
204            1              8
205            2              8
206            3              8
39 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
206 2010-08-19  232.28  228.78  232.63  228.68          231          33  2010
207 2010-08-20  231.73  230.98  232.18  230.33          232          33  2010
208 2010-08-22  231.63  231.63  231.63  231.63          234          33  2010
209 2010-08-23  230.73  232.18  234.08  230.73          235          34  2010
210 2010-08-24  229.58  229.03  231.68  227.83          236          34  2010
211 2010-08-25  226.03  227.68  228.83  226.03          237          34  2010
212 2010-08-26  225.43  227.08  227.43  225.43          238          34  2010

     day_of_week  year_of_month
206            3              8
207            4              8
208            6              8
209            0              8
210            1              8
211            2              8
212            3              8
40 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
212 2010-08-26  225.43  227.08  227.43  225.43          238          34  2010
213 2010-08-27  225.23  224.68  225.93  224.08          239          34  2010
214 2010-08-29  225.38  225.38  225.38  225.38          241          34  2010
215 2010-08-30  229.88  227.83  229.88  227.53          242          35  2010
216 2010-08-31  226.68  228.28  228.58  226.33          243          35  2010
217 2010-09-01  229.98  227.53  230.33  227.33          244          35  2010
218 2010-09-02  231.63  232.23  232.33  229.88          245          35  2010

     day_of_week  year_of_month
212            3              8
213            4              8
214            6              8
215            0              8
216            1              8
217            2              9
218            3              9
41 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
218 2010-09-02  231.63  232.23  232.33  229.88          245          35  2010
219 2010-09-03  231.33  232.03  232.63  231.33          246          35  2010
220 2010-09-05  231.33  231.33  231.33  231.33          248          35  2010
221 2010-09-06  233.38  232.63  233.38  232.33          249          36  2010
222 2010-09-07  232.53  232.78  233.38  232.53          250          36  2010
223 2010-09-08  232.18  232.53  232.95  231.08          251          36  2010
224 2010-09-09  233.18  232.83  233.88  231.43          252          36  2010

     day_of_week  year_of_month
218            3              9
219            4              9
220            6              9
221            0              9
222            1              9
223            2              9
224            3              9
42 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
224 2010-09-09  233.18  232.83  233.88  231.43          252          36  2010
225 2010-09-10  236.13  234.68  236.93  234.13          253          36  2010
226 2010-09-12  235.78  235.78  235.78  235.78          255          36  2010
227 2010-09-13  238.03  237.28  238.43  236.83          256          37  2010
228 2010-09-14  237.78  238.23  238.53  237.38          257          37  2010
229 2010-09-15  238.68  238.03  239.33  237.48          258          37  2010
230 2010-09-16  237.03  238.38  238.83  237.03          259          37  2010

     day_of_week  year_of_month
224            3              9
225            4              9
226            6              9
227            0              9
228            1              9
229            2              9
230            3              9
43 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
287 2010-12-09  261.08  257.67  261.50  257.33          343          49  2010
288 2010-12-10  261.80  260.48  261.80  260.08          344          49  2010
289 2010-12-12  261.80  261.80  261.80  261.80          346          49  2010
290 2010-12-13  263.12  262.17  263.12  260.87          347          50  2010
291 2010-12-14  264.08  263.17  264.08  262.42          348          50  2010
292 2010-12-15  264.73  263.67  264.73  263.02          349          50  2010
293 2010-12-16  263.98  263.73  265.23  263.17          350          50  2010

     day_of_week  year_of_month
287            3             12
288            4             12
289            6             12
290            0             12
291            1             12
292            2             12
293            3             12
56 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
318 2011-01-20  278.02  278.48  279.08  277.58           20           3  2011
319 2011-01-21  272.75  277.92  277.92  272.33           21           3  2011
320 2011-01-23  272.48  272.48  272.48  272.48           23           3  2011
321 2011-01-24  274.42  272.27  274.87  272.12           24           4  2011
322 2011-01-25  275.83  275.77  277.98  275.37           25           4  2011
323 2011-01-26  279.02  277.40  279.48  277.02           26           4  2011
324 2011-01-27  279.33  279.73  280.42  278.87           27           4  2011

     day_of_week  year_of_month
318            3              1
319            4              1
320            6              1
321            0              1
322            1              1
323            2              1
324            3              1
62 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
545 2011-12-08  250.43  250.23  251.88  247.75          342          49  2011
546 2011-12-09  243.23  245.98  246.88  243.18          343          49  2011
547 2011-12-11  243.53  243.53  243.53  243.53          345          49  2011
548 2011-12-12  247.93  247.58  247.93  245.93          346          50  2011
549 2011-12-13  242.23  245.03  245.03  241.88          347          50  2011
550 2011-12-14  241.13  240.40  242.43  239.93          348          50  2011
551 2011-12-15  235.13  237.53  238.68  234.73          349          50  2011

     day_of_week  year_of_month
545            3             12
546            4             12
547            6             12
548            0             12
549            1             12
550            2             12
551            3             12
108 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
556 2011-12-22  240.13  239.08  240.13  238.38          356          51  2011
557 2011-12-23  242.98  242.28  244.18  241.98          357          51  2011
558 2011-12-25  242.83  242.83  242.83  242.83          359          51  2011
559 2011-12-26  242.83  242.83  242.83  242.83          360          52  2011

          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
754 2012-10-04  263.85  264.30  264.85  261.80          278          40  2012
755 2012-10-05  264.10  265.05  265.90  263.70          279          40  2012
756 2012-10-07  264.08  264.08  264.08  264.08          281          40  2012
757 2012-10-08  262.15  263.50  263.70  261.20          282          41  2012
758 2012-10-09  262.00  261.80  263.70  261.65          283          41  2012
759 2012-10-10  256.70  259.00  259.20  256.50          284          41  2012
760 2012-10-11  254.25  254.20  256.50  252.05          285          41  2012

     day_of_week  year_of_month
754            3             10
755            4             10
756            6             10
757            0             10
758            1             10
759            2             10
760            3             10
151 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
760 2012-10-11  254.25  254.20  256.50  252.05          285          41  2012
761 2012-10-12  253.40  254.65  255.20  252.85          286          41  2012
762 2012-10-14  253.43  253.43  253.43  253.43          288          41  2012
763 2012-10-15  253.10  252.60  254.65  251.90          289          42  2012
764 2012-10-16  255.10  255.15  255.50  253.80          290          42  2012
765 2012-10-17  257.30  256.50  258.75  256.35          291          42  2012
766 2012-10-18  258.60  258.15  258.95  257.55          292          42  2012

     day_of_week  year_of_month
760            3             10
761            4             10
762            6             10
763            0             10
764            1             10
765            2             10
766            3             10
152 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
796 2012-11-29  255.20  253.35  255.50  253.25          334          48  2012
797 2012-11-30  255.45  254.75  256.75  254.30          335          48  2012
798 2012-12-02  255.43  255.43  255.43  255.43          337          48  2012
799 2012-12-03  256.00  255.85  256.90  255.25          338          49  2012
800 2012-12-04  254.90  255.00  255.55  254.05          339          49  2012
801 2012-12-05  257.20  255.00  257.40  254.65          340          49  2012
802 2012-12-06  257.55  257.00  258.30  256.65          341          49  2012

     day_of_week  year_of_month
796            3             11
797            4             11
798            6             12
799            0             12
800            1             12
801            2             12
802            3             12
159 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
818 2012-12-31  265.98  265.98  265.98  265.98          366          53  2012
819 2013-01-02  271.20  267.80  271.20  267.75            2           1  2013
820 2013-01-03  269.80  273.00  273.20  269.35            3           1  2013
821 2013-01-04  268.10  269.85  270.25  267.55            4           1  2013
822 2013-01-07  268.20  268.10  268.75  266.05            7           2  2013
823 2013-01-08  265.40  267.55  268.10  265.10            8           2  2013
824 2013-01-09  264.35  265.90  266.75  264.10            9           2  2013
825 2013-01-10  266.20  264.40  267.25  263.45           10           2  2013

     day_of_week  year_of_month
818            0             12
819            2              1
820            3              1
821            4              1
822            0              1
823            1              1
824            2              1
825            3              1
164 ========
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
830 2013-01-17  261.95  263.00  263.15  259.90           17           3  2013
831 2013-01-18  262.65  264.00  264.10  261.10           18           3  2013
832 2013-01-20  262.42  262.42  262.42  262.42           20           3  2013
833 2013-01-21  263.00  262.80  264.15  260.50           21           4  2013
834 2013-01-22  264.75  263.20  264.75  262.10           22           4  2013
835 2013-01-23  261.80  265.10  265.85  261.35           23           4  2013
836 2013-01-24  259.65  261.05  262.25  259.25           24           4  2013

     day_of_week  year_of_month
830            3              1
831            4              1
832            6              1
833            0              1
834            1              1
835            2              1
836            3              1
167 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1045 2013-11-21  262.20  266.10  266.20  261.15          325          47
1046 2013-11-22  263.80  263.60  265.50  262.20          326          47
1047 2013-11-24  263.77  263.77  263.77  263.77          328          47
1048 2013-11-25  266.30  265.45  268.55  265.35          329          48
1049 2013-11-26  267.30  264.40  267.40  262.70          330          48
1050 2013-11-27  267.80  265.60  268.10  264.40          331          48
1051 2013-11-28  270.00  269.50  271.15  269.45          332          48

      year  day_of_week  year_of_month
1045  2013            3             11
1046  2013            4             11
1047  2013            6             11
1048  2013            0             11
1049  2013            1             11
1050  2013            2             11
1051  2013            3             11
211 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1072 2013-12-30  265.65  266.30  266.45  265.05          364          53
1073 2014-01-01  265.98  265.98  265.98  265.98            1           1
1074 2014-01-02  258.40  266.60  266.65  258.40            2           1
1075 2014-01-03  255.25  258.35  258.55  254.00            3           1
1076 2014-01-06  255.85  255.45  257.85  254.70            6           2
1077 2014-01-07  257.05  254.90  258.10  254.90            7           2
1078 2014-01-08  256.80  257.85  258.30  255.35            8           2
1079 2014-01-09  255.50  256.90  257.30  255.20            9           2

      year  day_of_week  year_of_month
1072  2013            0             12
1073  2014            2              1
1074  2014            3              1
1075  2014            4              1
1076  2014            0              1
1077  2014            1              1
1078  2014            2              1
1079  2014            3              1
218 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1137 2014-04-03  260.65  260.65  262.40  260.15           93          14
1138 2014-04-04  261.40  260.45  262.00  260.25           94          14
1139 2014-04-05  261.40  261.40  261.40  261.40           95          14
1140 2014-04-07  260.45  260.20  261.35  259.40           97          15
1141 2014-04-08  262.55  259.80  262.55  259.55           98          15
1142 2014-04-09  262.40  262.75  263.25  262.10           99          15
1143 2014-04-10  262.70  263.60  264.05  262.30          100          15

      year  day_of_week  year_of_month
1137  2014            3              4
1138  2014            4              4
1139  2014            5              4
1140  2014            0              4
1141  2014            1              4
1142  2014            2              4
1143  2014            3              4
231 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1205 2014-07-10  259.80  260.00  260.60  259.30          191          28
1206 2014-07-11  257.80  258.15  258.45  257.00          192          28
1207 2014-07-12  257.80  257.80  257.80  257.80          193          28
1208 2014-07-13  257.80  257.80  257.80  257.80          194          28
1209 2014-07-14  258.50  258.95  259.60  257.95          195          29
1210 2014-07-15  261.35  259.45  262.10  259.30          196          29
1211 2014-07-16  261.85  261.45  262.40  261.10          197          29
1212 2014-07-17  262.50  262.40  263.70  262.25          198          29

      year  day_of_week  year_of_month
1205  2014            3              7
1206  2014            4              7
1207  2014            5              7
1208  2014            6              7
1209  2014            0              7
1210  2014            1              7
1211  2014            2              7
1212  2014            3              7
245 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1212 2014-07-17  262.50  262.40  263.70  262.25          198          29
1213 2014-07-18  262.30  260.65  262.30  260.50          199          29
1214 2014-07-20  262.30  262.30  262.30  262.30          201          29
1215 2014-07-21  262.20  263.30  264.30  262.20          202          30
1216 2014-07-22  264.00  262.20  264.10  262.20          203          30
1217 2014-07-23  263.60  264.45  264.70  263.40          204          30
1218 2014-07-24  264.05  264.00  265.15  263.35          205          30

      year  day_of_week  year_of_month
1212  2014            3              7
1213  2014            4              7
1214  2014            6              7
1215  2014            0              7
1216  2014            1              7
1217  2014            2              7
1218  2014            3              7
246 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1218 2014-07-24  264.05  264.00  265.15  263.35          205          30
1219 2014-07-25  264.95  264.25  264.95  263.95          206          30
1220 2014-07-27  264.95  264.95  264.95  264.95          208          30
1221 2014-07-28  266.90  264.90  267.50  264.65          209          31
1222 2014-07-29  269.85  267.80  269.85  267.50          210          31
1223 2014-07-30  272.95  270.25  274.60  269.95          211          31
1224 2014-07-31  271.65  272.50  273.90  271.10          212          31

      year  day_of_week  year_of_month
1218  2014            3              7
1219  2014            4              7
1220  2014            6              7
1221  2014            0              7
1222  2014            1              7
1223  2014            2              7
1224  2014            3              7
247 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1229 2014-08-07  266.25  267.15  267.55  265.60          219          32
1230 2014-08-08  263.10  265.65  265.75  262.45          220          32
1231 2014-08-10  263.10  263.10  263.10  263.10          222          32
1232 2014-08-11  264.80  265.15  265.15  263.80          223          33
1233 2014-08-12  264.65  264.95  266.30  264.45          224          33
1234 2014-08-13  266.40  265.20  266.45  264.40          225          33
1235 2014-08-14  267.00  266.50  268.25  265.70          226          33

      year  day_of_week  year_of_month
1229  2014            3              8
1230  2014            4              8
1231  2014            6              8
1232  2014            0              8
1233  2014            1              8
1234  2014            2              8
1235  2014            3              8
249 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1253 2014-09-11  261.50  262.80  263.35  261.50          254          37
1254 2014-09-12  262.80  262.20  263.20  261.75          255          37
1255 2014-09-13  262.80  262.80  262.80  262.80          256          37
1256 2014-09-15  262.25  261.65  262.45  260.65          258          38
1257 2014-09-16  262.55  262.55  263.05  261.90          259          38
1258 2014-09-17  265.45  264.05  265.45  263.85          260          38
1259 2014-09-18  264.10  265.05  265.10  263.25          261          38

      year  day_of_week  year_of_month
1253  2014            3              9
1254  2014            4              9
1255  2014            5              9
1256  2014            0              9
1257  2014            1              9
1258  2014            2              9
1259  2014            3              9
254 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1264 2014-09-25  260.15  261.30  261.60  259.65          268          39
1265 2014-09-26  259.45  258.30  259.50  258.20          269          39
1266 2014-09-27  259.45  259.45  259.45  259.45          270          39
1267 2014-09-29  258.50  259.45  260.10  258.15          272          40
1268 2014-09-30  257.00  258.25  258.90  256.50          273          40
1269 2014-10-01  254.40  256.40  256.50  253.90          274          40
1270 2014-10-02  250.90  252.80  252.80  249.85          275          40

      year  day_of_week  year_of_month
1264  2014            3              9
1265  2014            4              9
1266  2014            5              9
1267  2014            0              9
1268  2014            1              9
1269  2014            2             10
1270  2014            3             10
256 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1299 2014-11-13  250.50  251.75  252.15  250.05          317          46
1300 2014-11-14  248.50  249.70  249.70  247.45          318          46
1301 2014-11-16  248.50  248.50  248.50  248.50          320          46
1302 2014-11-17  249.25  247.85  249.55  247.35          321          47
1303 2014-11-18  251.25  250.10  251.70  250.10          322          47
1304 2014-11-19  250.50  252.00  252.00  250.20          323          47
1305 2014-11-20  250.10  249.85  250.65  248.90          324          47

      year  day_of_week  year_of_month
1299  2014            3             11
1300  2014            4             11
1301  2014            6             11
1302  2014            0             11
1303  2014            1             11
1304  2014            2             11
1305  2014            3             11
263 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1315 2014-12-04  254.85  252.20  254.90  252.15          338          49
1316 2014-12-05  254.35  254.45  255.00  254.15          339          49
1317 2014-12-07  253.15  253.15  253.15  253.15          341          49
1318 2014-12-08  252.75  253.15  253.85  252.65          342          50
1319 2014-12-09  251.95  252.05  252.45  251.35          343          50
1320 2014-12-10  247.40  251.20  251.20  247.40          344          50
1321 2014-12-11  244.85  245.85  246.70  244.40          345          50

      year  day_of_week  year_of_month
1315  2014            3             12
1316  2014            4             12
1317  2014            6             12
1318  2014            0             12
1319  2014            1             12
1320  2014            2             12
1321  2014            3             12
266 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1343 2015-01-15  247.40  246.00  247.40  245.40           15           3
1344 2015-01-16  243.15  244.95  244.95  242.45           16           3
1345 2015-01-17  243.15  243.15  243.15  243.15           17           3
1346 2015-01-19  246.50  244.75  246.70  244.60           19           4
1347 2015-01-20  247.90  246.50  248.40  246.50           20           4
1348 2015-01-21  248.80  247.40  249.00  247.30           21           4
1349 2015-01-22  249.65  250.05  250.85  249.35           22           4

      year  day_of_week  year_of_month
1343  2015            3              1
1344  2015            4              1
1345  2015            5              1
1346  2015            0              1
1347  2015            1              1
1348  2015            2              1
1349  2015            3              1
273 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1349 2015-01-22  249.65  250.05  250.85  249.35           22           4
1350 2015-01-23  251.20  252.90  252.90  250.55           23           4
1351 2015-01-25  251.20  251.20  251.20  251.20           25           4
1352 2015-01-26  250.95  249.75  251.15  249.05           26           5
1353 2015-01-27  252.70  252.05  252.80  251.55           27           5
1354 2015-01-28  252.65  251.55  253.10  251.50           28           5
1355 2015-01-29  252.00  250.70  252.75  250.40           29           5

      year  day_of_week  year_of_month
1349  2015            3              1
1350  2015            4              1
1351  2015            6              1
1352  2015            0              1
1353  2015            1              1
1354  2015            2              1
1355  2015            3              1
274 ========
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1384 2015-03-12  252.75  252.45  253.80  251.75           71          11
1385 2015-03-13  253.60  253.55  254.05  252.90           72          11
1386 2015-03-14  253.60  253.60  253.60  253.60           73          11
1387 2015-03-16  254.10  252.90  254.20  252.90           75          12
1388 2015-03-17  259.45  255.00  259.90  254.70           76          12
1389 2015-03-18  260.00  259.90  260.85  259.70           77          12
1390 2015-03-19  260.60  261.60  261.85  260.15           78          12

      year  day_of_week  year_of_month
1384  2015            3              3
1385  2015            4              3
1386  2015            5              3
1387  2015            0              3
1388  2015            1              3
1389  2015            2              3
1390  2015            3              3
281 ========

           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
2565 2019-12-30  295.20  295.80  296.55  294.85          364          53
2566 2020-01-02  290.75  294.65  295.55  290.75            2           1
2567 2020-01-03  291.50  293.75  295.55  289.65            3           1
2568 2020-01-06  289.00  289.00  290.10  288.35            6           2
2569 2020-01-07  292.40  290.35  293.10  290.10            7           2
2570 2020-01-08  290.15  289.90  291.65  288.05            8           2
2571 2020-01-09  295.00  293.95  295.40  292.90            9           2

      year  day_of_week  year_of_month
2565  2019            0             12
2566  2020            3              1
2567  2020            4              1
2568  2020            0              1
2569  2020            1              1
2570  2020            2              1
2571  2020            3              1
531 ========

In [174]:
df2 = info_dataFrame[info_dataFrame["timedelta"]>timedelta(weeks = 1)]
df2  = df2.reset_index(drop = True)

In [175]:
for i in range(len(df2)):
    df_table = df.loc[(df.time.between(df2.iloc[i].시작일,df2.iloc[i].time))]
    
    print(df_table)
#     time.sleep(0.5)

          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
185 2010-07-22  226.63  227.68  229.08  226.63          203          29  2010
186 2010-07-23  229.78  229.48  230.48  228.48          204          29  2010
187 2010-07-25  230.08  230.08  230.08  230.08          206          29  2010
188 2010-07-26  231.38  230.38  231.73  230.28          207          30  2010
189 2010-07-27  231.68  231.88  232.33  231.33          208          30  2010
190 2010-07-30  230.18  231.73  232.08  229.83          211          30  2010

     day_of_week  year_of_month
185            3              7
186            4              7
187            6              7
188            0              7
189            1              7
190            4              7
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
189 2010-07-27  231.68  231.88  232.33  231.33          208          30  2010
190 2010-07-30  230.18  231.73  232.08  229.83          211          30  2010
191 2010-08-01  230.08  230.08  230.08  230.08          213          30  2010
192 2010-08-02  233.33  231.48  233.73  231.28          214          31  2010
193 2010-08-03  234.13  234.33  234.48  233.73          215          31  2010
194 2010-08-04  233.68  234.43  234.48  232.58          216          31  2010
195 2010-08-05  233.63  234.88  235.18  232.18          217          31  2010

     day_of_week  year_of_month
189            1              7
190            4              7
191            6              8
192            0              8
193            1              8
194            2              8
195            3              8
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
230 2010-09-16  237.03  238.38  238.83  237.03          259          37  2010
231 2010-09-17  238.58  238.48  239.38  237.23          260          37  2010
232 2010-09-20  239.63  238.03  240.03  237.38          263          38  2010
233 2010-09-24  240.48  239.18  240.93  238.38          267          38  2010

     day_of_week  year_of_month
230            3              9
231            4              9
232            0              9
233            4              9
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
232 2010-09-20  239.63  238.03  240.03  237.38          263          38  2010
233 2010-09-24  240.48  239.18  240.93  238.38          267          38  2010
234 2010-09-27  242.33  241.83  242.73  241.48          270          39  2010
235 2010-09-28  242.18  242.33  242.58  241.88          271          39  2010
236 2010-09-29  243.68  242.73  244.93  242.58          272          39  2010
237 2010-09-30  244.18  243.83  244.18  243.28          273          39  2010

     day_of_week  year_of_month
232            0              9
233            4              9
234            0              9
235            1              9
236            2              9
237            3              9
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
324 2011-01-27  279.33  279.73  280.42  278.87           27           4  2011
325 2011-01-28  278.98  279.42  279.87  277.12           28           4  2011
326 2011-01-31  273.27  275.25  276.48  273.27           31           5  2011
327 2011-02-01  273.92  275.12  275.52  273.48           32           5  2011
328 2011-02-02  273.92  273.92  273.92  273.92           33           5  2011
329 2011-02-04  273.92  273.92  273.92  273.92           35           5  2011

     day_of_week  year_of_month
324            3              1
325            4              1
326            0              1
327            1              2
328            2              2
329            4              2
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
328 2011-02-02  273.92  273.92  273.92  273.92           33           5  2011
329 2011-02-04  273.92  273.92  273.92  273.92           35           5  2011
330 2011-02-07  274.42  277.77  278.98  274.42           38           6  2011
331 2011-02-08  272.73  275.73  276.08  272.73           39           6  2011
332 2011-02-09  269.55  273.87  274.02  269.08           40           6  2011
333 2011-02-10  264.92  268.45  269.52  264.48           41           6  2011

     day_of_week  year_of_month
328            2              2
329            4              2
330            0              2
331            1              2
332            2              2
333            3              2
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
599 2012-02-23  264.58  265.58  265.80  263.62           54           8  2012
600 2012-02-24  265.98  264.37  266.33  263.12           55           8  2012
601 2012-02-27  262.17  265.33  265.52  261.58           58           9  2012
602 2012-02-28  264.37  263.12  264.67  262.58           59           9  2012
603 2012-02-29  267.23  265.57  268.23  265.57           60           9  2012
604 2012-03-02  267.92  269.27  269.67  267.62           62           9  2012

     day_of_week  year_of_month
599            3              2
600            4              2
601            0              2
602            1              2
603            2              2
604            4              3
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
603 2012-02-29  267.23  265.57  268.23  265.57           60           9  2012
604 2012-03-02  267.92  269.27  269.67  267.62           62           9  2012
605 2012-03-05  267.00  268.60  268.95  266.25           65          10  2012
606 2012-03-06  264.92  267.32  268.17  263.42           66          10  2012
607 2012-03-07  262.58  261.33  263.17  260.40           67          10  2012
608 2012-03-08  266.42  263.00  266.48  261.83           68          10  2012

     day_of_week  year_of_month
603            2              2
604            4              3
605            0              3
606            1              3
607            2              3
608            3              3
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
818 2012-12-31  265.98  265.98  265.98  265.98          366          53  2012
819 2013-01-02  271.20  267.80  271.20  267.75            2           1  2013
820 2013-01-03  269.80  273.00  273.20  269.35            3           1  2013
821 2013-01-04  268.10  269.85  270.25  267.55            4           1  2013
822 2013-01-07  268.20  268.10  268.75  266.05            7           2  2013
823 2013-01-08  265.40  267.55  268.10  265.10            8           2  2013
824 2013-01-09  264.35  265.90  266.75  264.10            9           2  2013
825 2013-01-10  266.20  264.40  267.25  263.45           10           2  2013

     day_of_week  year_of_month
818            0             12
819            2              1
820            3              1
821            4              1
822            0              1
823            1              1
824            2              1
825            3              1
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
923 2013-05-30  261.85  261.50  262.90  261.15          150          22  2013
924 2013-05-31  262.30  262.55  263.90  262.10          151          22  2013
925 2013-06-03  261.30  261.20  262.15  260.70          154          23  2013
926 2013-06-04  260.85  262.35  262.35  259.05          155          23  2013
927 2013-06-05  256.55  260.50  260.75  256.55          156          23  2013
928 2013-06-07  251.10  256.05  256.60  250.45          158          23  2013

     day_of_week  year_of_month
923            3              5
924            4              5
925            0              6
926            1              6
927            2              6
928            4              6
          time      종가      오픈      고가      저가  day_of_year  weekofyear  year  \
927 2013-06-05  256.55  260.50  260.75  256.55          156          23  2013
928 2013-06-07  251.10  256.05  256.60  250.45          158          23  2013
929 2013-06-10  252.70  251.40  252.70  250.65          161          24  2013
930 2013-06-11  250.75  252.50  252.55  248.70          162          24  2013
931 2013-06-12  248.85  249.45  250.45  247.90          163          24  2013
932 2013-06-13  244.49  247.60  248.30  244.40          164          24  2013

     day_of_week  year_of_month
927            2              6
928            4              6
929            0              6
930            1              6
931            2              6
932            3              6
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
997  2013-09-12  262.32  262.70  265.15  261.85          255          37
998  2013-09-13  263.10  263.00  265.10  262.60          256          37
999  2013-09-16  265.50  266.45  267.20  265.20          259          38
1000 2013-09-17  264.20  265.10  265.30  263.30          260          38
1001 2013-09-18  264.02  264.02  264.02  264.02          261          38
1002 2013-09-23  264.95  264.20  266.55  262.35          266          39

      year  day_of_week  year_of_month
997   2013            3              9
998   2013            4              9
999   2013            0              9
1000  2013            1              9
1001  2013            2              9
1002  2013            0              9
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1001 2013-09-18  264.02  264.02  264.02  264.02          261          38
1002 2013-09-23  264.95  264.20  266.55  262.35          266          39
1003 2013-09-24  264.70  263.20  265.10  262.60          267          39
1004 2013-09-25  263.05  264.90  265.10  262.35          268          39
1005 2013-09-26  265.60  262.35  265.60  261.85          269          39

      year  day_of_week  year_of_month
1001  2013            2              9
1002  2013            0              9
1003  2013            1              9
1004  2013            2              9
1005  2013            3              9
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1072 2013-12-30  265.65  266.30  266.45  265.05          364          53
1073 2014-01-01  265.98  265.98  265.98  265.98            1           1
1074 2014-01-02  258.40  266.60  266.65  258.40            2           1
1075 2014-01-03  255.25  258.35  258.55  254.00            3           1
1076 2014-01-06  255.85  255.45  257.85  254.70            6           2
1077 2014-01-07  257.05  254.90  258.10  254.90            7           2
1078 2014-01-08  256.80  257.85  258.30  255.35            8           2
1079 2014-01-09  255.50  256.90  257.30  255.20            9           2

      year  day_of_week  year_of_month
1072  2013            0             12
1073  2014            2              1
1074  2014            3              1
1075  2014            4              1
1076  2014            0              1
1077  2014            1              1
1078  2014            2              1
1079  2014            3              1
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1089 2014-01-23  254.60  257.90  258.05  254.50           23           4
1090 2014-01-24  253.40  253.55  254.15  251.60           24           4
1091 2014-01-27  250.20  249.50  251.30  248.25           27           5
1092 2014-01-28  251.25  249.50  251.40  249.15           28           5
1093 2014-01-29  254.50  252.20  254.50  251.90           29           5
1094 2014-02-03  250.80  252.50  252.90  249.95           34           6

      year  day_of_week  year_of_month
1089  2014            3              1
1090  2014            4              1
1091  2014            0              1
1092  2014            1              1
1093  2014            2              1
1094  2014            0              2
           time      종가      오픈     고가      저가  day_of_year  weekofyear  year  \
1093 2014-01-29  254.50  252.20  254.5  251.90           29           5  2014
1094 2014-02-03  250.80  252.50  252.9  249.95           34           6  2014
1095 2014-02-04  246.05  247.50  247.6  245.25           35           6  2014
1096 2014-02-05  246.55  247.10  247.6  245.55           36           6  2014
1097 2014-02-06  248.40  247.55  249.7  247.30           37           6  2014

      day_of_week  year_of_month
1093            2              1
1094            0              2
1095            1              2
1096            2              2
1097            3              2
           time      종가     오픈      고가      저가  day_of_year  weekofyear  year  \
1270 2014-10-02  250.90  252.8  252.80  249.85          275          40  2014
1271 2014-10-05  250.90  250.9  250.90  250.90          278          40  2014
1272 2014-10-06  250.85  252.0  252.10  250.15          279          41  2014
1273 2014-10-07  250.80  251.6  252.05  250.05          280          41  2014
1274 2014-10-08  250.30  249.2  250.55  248.75          281          41  2014
1275 2014-10-10  245.60  247.1  247.25  245.05          283          41  2014

      day_of_week  year_of_month
1270            3             10
1271            6             10
1272            0             10
1273            1             10
1274            2             10
1275            4             10
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1274 2014-10-08  250.30  249.20  250.55  248.75          281          41
1275 2014-10-10  245.60  247.10  247.25  245.05          283          41
1276 2014-10-13  246.10  243.25  246.10  243.25          286          42
1277 2014-10-14  244.80  246.30  247.20  244.80          287          42
1278 2014-10-15  245.50  245.40  246.30  243.90          288          42
1279 2014-10-16  243.65  242.90  244.35  242.15          289          42

      year  day_of_week  year_of_month
1274  2014            2             10
1275  2014            4             10
1276  2014            0             10
1277  2014            1             10
1278  2014            2             10
1279  2014            3             10
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1326 2014-12-18  242.45  245.10  245.50  240.90          352          51
1327 2014-12-19  246.50  245.65  246.90  244.65          353          51
1328 2014-12-22  247.80  246.95  248.25  246.10          356          52
1329 2014-12-23  247.20  248.00  248.15  247.20          357          52
1330 2014-12-24  248.35  247.20  248.75  247.10          358          52
1331 2014-12-26  248.90  248.70  249.75  248.30          360          52

      year  day_of_week  year_of_month
1326  2014            3             12
1327  2014            4             12
1328  2014            0             12
1329  2014            1             12
1330  2014            2             12
1331  2014            4             12
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1330 2014-12-24  248.35  247.20  248.75  247.10          358          52
1331 2014-12-26  248.90  248.70  249.75  248.30          360          52
1332 2014-12-29  247.40  249.60  249.85  247.40          363          53
1333 2014-12-30  244.00  247.65  248.30  244.00          364          53
1334 2015-01-02  245.50  244.00  245.70  243.90            2           1
1335 2015-01-05  244.75  244.30  245.45  242.45            5           2

      year  day_of_week  year_of_month
1330  2014            2             12
1331  2014            4             12
1332  2014            0             12
1333  2014            1             12
1334  2015            4              1
1335  2015            0              1
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1333 2014-12-30  244.00  247.65  248.30  244.00          364          53
1334 2015-01-02  245.50  244.00  245.70  243.90            2           1
1335 2015-01-05  244.75  244.30  245.45  242.45            5           2
1336 2015-01-06  240.50  242.05  242.60  239.75            6           2
1337 2015-01-07  241.05  240.10  241.15  239.70            7           2
1338 2015-01-08  243.95  242.30  244.70  242.05            8           2

      year  day_of_week  year_of_month
1333  2014            1             12
1334  2015            4              1
1335  2015            0              1
1336  2015            1              1
1337  2015            2              1
1338  2015            3              1
           time      종가      오픈      고가     저가  day_of_year  weekofyear  year  \
1583 2015-12-24  242.40  245.85  246.05  242.4          358          52  2015
1584 2015-12-28  239.80  243.45  243.60  239.8          362          53  2015
1585 2015-12-29  242.40  240.60  242.40  239.3          363          53  2015
1586 2015-12-30  240.45  242.50  242.95  240.3          364          53  2015
1587 2016-01-04  235.00  239.35  239.35  234.7            4           1  2016

      day_of_week  year_of_month
1583            3             12
1584            0             12
1585            1             12
1586            2             12
1587            0              1
           time      종가      오픈      고가     저가  day_of_year  weekofyear  year  \
1586 2015-12-30  240.45  242.50  242.95  240.3          364          53  2015
1587 2016-01-04  235.00  239.35  239.35  234.7            4           1  2016
1588 2016-01-05  236.40  234.90  237.40  234.9            5           1  2016
1589 2016-01-06  235.45  236.70  236.70  233.7            6           1  2016
1590 2016-01-07  232.50  234.30  235.20  232.0            7           1  2016

      day_of_week  year_of_month
1586            2             12
1587            0              1
1588            1              1
1589            2              1
1590            3              1
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1665 2016-04-28  246.45  250.10  250.30  246.45          119          17
1666 2016-04-29  245.35  246.60  246.70  244.50          120          17
1667 2016-05-02  244.25  244.95  245.10  243.60          123          18
1668 2016-05-03  244.45  244.90  244.90  243.85          124          18
1669 2016-05-04  243.35  243.20  243.85  242.40          125          18
1670 2016-05-09  242.55  243.45  243.45  242.10          130          19

      year  day_of_week  year_of_month
1665  2016            3              4
1666  2016            4              4
1667  2016            0              5
1668  2016            1              5
1669  2016            2              5
1670  2016            0              5
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1669 2016-05-04  243.35  243.20  243.85  242.40          125          18
1670 2016-05-09  242.55  243.45  243.45  242.10          130          19
1671 2016-05-10  243.80  241.95  243.80  241.95          131          19
1672 2016-05-11  242.80  244.30  244.30  242.00          132          19
1673 2016-05-12  242.90  242.35  243.30  241.70          133          19

      year  day_of_week  year_of_month
1669  2016            2              5
1670  2016            0              5
1671  2016            1              5
1672  2016            2              5
1673  2016            3              5
           time      종가      오픈      고가      저가  day_of_year  weekofyear  \
1756 2016-09-08  260.86  260.70  261.45  259.55          252          36
1757 2016-09-09  258.00  259.20  259.65  257.20          253          36
1758 2016-09-12  251.70  253.50  254.50  251.15          256          37
1759 2016-09-13  252.05  254.60  254.60  251.90          257          37
1760 2016-09-19  254.60  251.05  254.85  251.00          263          38

      year  day_of_week  year_of_month
1756  2016            3              9
1757  2016            4              9
1758  2016            0              9
1759  2016            1              9
1760  2016            0              9

### 여기서부터 기술적 지표

In [177]:
WINDOW  = 3 # 몇 단튀(ex일)로 할것인지.

# 단순 이동 평균(Simple Moving Average, SMA)
def SMA(data, period=30, column='Close'):
    return data[column].rolling(window=period).mean()

# 지수 이동 평균(Exponential Moving Average, EMA)
def EMA(data, period=3, column='Close'):
    return data[column].ewm(span=period, adjust=False).mean()

def WMA(data, period=3, column='Close'): #가중이동평균
    val = []
    for i in range(WINDOW):
        val.append(None)

    for i in range(len(data)-period):
        df = data[[column]].loc[i+1:i+period].reset_index(drop = True)
        sum_count_1 = 0
        sum_count_2 = 0
        for j in range(period):
            sum_count_1 = sum_count_1 + (j+1) * float(df.iloc[j].values)
            sum_count_2 = sum_count_2 + (j+1)
        val.append(sum_count_1/sum_count_2)
    return val

def LSMA(data, period=3, column='Close'): # 최소제솝평균..

    val = []
    for i in range(WINDOW):
        val.append(None)

    for i in range(len(data)-period):
        df = data[[column]].loc[i+1:i+period].reset_index(drop = True)
        X = [k+1 for k in range(period)]
        Y = [float(df.iloc[k]) for k in range(period)]
        LRS = (len(X) * sum([X[i]*Y[i] for i in range(len(X))])- sum(X)*sum(Y)) /(len(X) * sum([X[i]*X[i] for i in range(len(X))]) - sum(X) * sum(X))
        LRT = (sum(Y) - LRS * sum(X)) / (len(X))
        LRI = LRT + LRS * len(X)
        val.append(LRI)

    return val

# data, period, column = data, WINDOW, '종가'
def triangular_weighted_moving_average(data, period=20, column='Close'):
    
    val = []
    for i in range(WINDOW):
        val.append(None)

    for i in range(len(data)-period):
        df = data[[column]].loc[i+1:i+period].reset_index(drop = True)
        
        A = int(np.ceil((period+0.1)/2)) # N기간을 2로나눔 (소수점 반올림)
        B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
        for_Trima = list(df[column].values)
        for_Trima.insert(0, B)
        Trima = np.mean(for_Trima)#B값의 A기간 이동평균값
        val.append(np.mean(Trima))
        
    return val

In [178]:
data = info_dataFrame.reset_index(drop = True).copy()

In [179]:
del data["timedelta"]

In [180]:
data

                    time      오픈      저가      고가      종가        시작일
0    2009-11-26 00:00:00  211.85  210.63  215.28  212.18 2009-11-19
1    2009-12-03 00:00:00  212.18  200.03  214.03  211.25 2009-11-26
2    2009-12-10 00:00:00  211.25  210.73  216.83  215.80 2009-12-03
3    2009-12-17 00:00:00  215.80  212.58  218.78  217.73 2009-12-10
4    2009-12-24 00:00:00  217.73  213.28  221.93  218.08 2009-12-17
..                   ...     ...     ...     ...     ...        ...
732  2023-11-09 00:00:00  316.05  315.25  335.30  325.95 2023-11-02
733  2023-11-16 00:00:00  325.95  322.15  335.95  334.35 2023-11-09
734  2023-11-23 00:00:00  334.35  331.50  338.75  337.45 2023-11-16
735  2023-11-30 00:00:00  337.45  333.30  339.20  337.05 2023-11-23
736  2023-12-07 00:00:00  337.05  331.50  339.20  331.80 2023-11-30

[737 rows x 6 columns]

In [181]:
data["단순이동평균_"+"종가"] = SMA(data, period=WINDOW, column='종가')
data["지수이동평균_"+"종가"] = EMA(data, period=WINDOW, column='종가')
data["가중이동평균_"+"종가"] = WMA(data, period=WINDOW, column='종가')
data["최소제곱평균_"+"종가"] = LSMA(data, period=WINDOW, column='종가')
data["삼각이동평균_"+"종가"] = triangular_weighted_moving_average(data, period=WINDOW, column='종가')

C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]

C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:35: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Y = [float(df.iloc[k]) for k in range(period)]

C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead

C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값
C:\Users\Happy\AppData\Local\Temp\ipykernel_17304\803968331.py:54: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  B = float(df.iloc[0:A].mean()) #A기간동안의 이동평균값

In [182]:
unname_list = ["단순이동평균_","지수이동평균_","가중이동평균_","최소제곱평균_","삼각이동평균_"]

In [183]:
val_col_list = set(data.columns)

In [184]:

val_col_list = set(data.columns) - {"시가","고가","저가","종가","날짜","오픈","time","진입시점","시작일"}
val_col_list = set(val_col_list)
val_col_list = list(val_col_list)

data['time'] = pd.to_datetime(data['time'], format='%Y-%m-%d', errors='raise')
# data['시작일'] = pd.to_datetime(data['시작일'], format='%Y-%m-%d', errors='raise')
data = data.fillna(0)

기술적지표 수요일 종가 output 현재 주가 비교 상방,하방

In [185]:
for l in unname_list:

    name = [s for s in val_col_list if l in s]
    if (name[0].find("종가")):
        data["종가"+"-"+str(name[0])] = data["종가"] - data[name[0]]
        data.loc[list(data.loc[(data[name[0]]==0)][name[0]].index),"종가"+"-"+str(name[0])] = 0 # 원래 0 이였던 값들을 찾은다음 다시 0 을 집어넣어줌.
        data.loc[(data["종가"+"-"+str(name[0])])> 0,l+"포지션"] = "상방"
        data.loc[(data["종가"+"-"+str(name[0])])< 0,l+"포지션"] = "하방"

In [186]:
data.to_csv(save_path+"ALL_DATA_KOSPI_spot_목종목시_2023.csv", encoding = "cp949")

In [198]:
data = data[1:].sort_values(by=["time"],ascending = False).reset_index(drop=True)

In [199]:
data.to_csv(save_path+"ALL_DATA_KOSPI_spot_목종목시_2023.csv", encoding = "cp949")

In [194]:
data.columns

Index(['time', '오픈', '저가', '고가', '종가', '시작일', '단순이동평균_종가', '지수이동평균_종가',
       '가중이동평균_종가', '최소제곱평균_종가', '삼각이동평균_종가', '종가-단순이동평균_종가', '단순이동평균_포지션',
       '종가-지수이동평균_종가', '지수이동평균_포지션', '종가-가중이동평균_종가', '가중이동평균_포지션',
       '종가-최소제곱평균_종가', '최소제곱평균_포지션', '종가-삼각이동평균_종가', '삼각이동평균_포지션'],
      dtype='object')

In [188]:
info_2 = {}
for j in tqdm(val_col_list):
    col_name = j
    
    info_2[col_name] = []
    
    for i in range(len(data)):
        if(data.iloc[i,:][col_name] == "None"):
            info_2[col_name].append(None)
        else:
            new_df = df.loc[df.time.between(data.iloc[i,:].시작일,data.iloc[i,:].time)]

            if (new_df.iloc[1,:].오픈 <= data.iloc[i,:][col_name]):
                state = "Long"
            else: # new_df.iloc[1,:].오픈 >= data.iloc[i,:][col_name])
                state = "Short"
#             print(state)

            if state == "Long":
                info_2[col_name].append(data.iloc[i,:][col_name] <= max(new_df.고가))
#                 print(data.iloc[i,:][col_name] , max(new_df.고가))

            elif state == "Short":
                info_2[col_name].append(data.iloc[i,:][col_name] >= min(new_df.저가))
#                 print(data.iloc[i,:][col_name] , min(new_df.저가))

info_2 = pd.DataFrame(info_2)
for j in val_col_list:
    print(j)
    print("총 날짜",len(info_2[(info_2[j] == True) |  (info_2[j] == False)][j]))
    print("맞은 날짜",sum((info_2[(info_2[j] == True) |  (info_2[j] == False)][j])))
    print("정답률",sum((info_2[(info_2[j] == True) |  (info_2[j] == False)][j]))/len(info_2[(info_2[j] == True) |  (info_2[j] == False)][j]))
    print("=====================================================================")

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.19s/it]

최소제곱평균_종가
총 날짜 737
맞은 날짜 717
정답률 0.9728629579375848
=====================================================================
단순이동평균_종가
총 날짜 737
맞은 날짜 655
정답률 0.8887381275440976
=====================================================================
가중이동평균_종가
총 날짜 737
맞은 날짜 727
정답률 0.9864314789687924
=====================================================================
지수이동평균_종가
총 날짜 737
맞은 날짜 684
정답률 0.9280868385345997
=====================================================================
삼각이동평균_종가
총 날짜 737
맞은 날짜 630
정답률 0.8548168249660787
=====================================================================

In [189]:
info_2.to_csv(save_path+"info_dataFrame2_spot_목종목시_2023.csv", encoding = "cp949")

In [190]:
info_2

     최소제곱평균_종가  단순이동평균_종가  가중이동평균_종가  지수이동평균_종가  삼각이동평균_종가
0        False      False      False       True      False
1        False      False      False       True      False
2        False       True      False       True      False
3         True       True       True       True       True
4         True       True       True       True       True
..         ...        ...        ...        ...        ...
732       True       True       True       True       True
733       True       True       True       True       True
734       True       True       True       True       True
735       True       True       True       True       True
736       True       True       True       True       True

[737 rows x 5 columns]